language: php

php:
  - 5.5
  - 5.6
  - nightly

matrix:
  allow_failures:
    - nightly

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-source

script: phpunit --coverage-text --verbose
